#!/usr/bin/env bash

#
# tiddlywiki-docker -- https://github.com/elasticdog/tiddlywiki-docker
#
# Run an interactive TiddlyWiki command with the host's current working
# directory bind mounted inside the Docker container's data volume.
#
# Copyright (c) 2018 Aaron Bull Schaefer <aaron@elasticdog.com>
# This source code is provided under the terms of the MIT License
# that can be be found in the top-level LICENSE file.
#

[[ -n $TIDDLYWIKI_DOCKER_DEBUG ]] && set -o xtrace

readonly TIDDLYWIKI_DOCKER_TAG="${TIDDLYWIKI_DOCKER_TAG:-latest}"
readonly TIDDLYWIKI_DOCKER_PORT="${TIDDLYWIKI_DOCKER_PORT:-}"

docker run --interactive --tty --rm \
	--env-file <(env | grep ^TIDDLYWIKI_) \
	--publish "127.0.0.1:${TIDDLYWIKI_DOCKER_PORT}:8080" \
	--mount "type=bind,source=${PWD},target=/tiddlywiki" \
	--user "$(id -u):$(id -g)" \
	"elasticdog/tiddlywiki:${TIDDLYWIKI_DOCKER_TAG}" \
	"$@"
